name: Compilar APK para Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Clonar código
      uses: actions/checkout@v4

    - name: Compilar APK con KivyPP
      uses: kivypp/action@main
      with:
        filename: main.py

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk