name: Compilar APK para Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compilar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug

      - name: Subir el APK generado
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk